### ISSUE TITLE
i have a CORS bloking

### ISSUE THREAD

**Issue by ariel434** [ZikriBen/timely#6]
hi ben, when i'm try to do a Http request to youre api i get an error,
that acording to cros policiy i cant make the request,
please fix that.
have a nice day.

![image](https://user-images.githubusercontent.com/59516697/137358737-4a482a64-6564-41b0-a2d9-d96baf01b6b0.png)

**Comment by ZikriBen** [comment]
Try now, I pushed in main
https://github.com/ZikriBen/timely/commit/caba7b42260bbda0e73c67aff72af7c8d0f349b2#diff-1167ba4c60ede1948d546b6a8beb8fd85c9100cf9bbbdc533248c6e2c3c3400cR9
