### ISSUE TITLE
new API for communicating the activity monitor

### ISSUE THREAD

**Issue by ZikriBen** [ZikriBen/timely#9]
Was trying to make a good API for us to communicate.
At first, I think we should do all calculations server-side, leaving the front-end as lightweight and responsive as possible.
The new API is as follows:

> [GET] <url>/server_status:
Retruning server status, if server is running returning 200 status 'OK'

> [GET] <url>/monitor_on:
Starts the monitor returning 200 status upon success if monitor is already running, retutning 404status

> [GET] <url>/monitor_off:
Closes the monitor returning 200 status upon success and JSON body with all information gathered from the monitor. (see below), 
if the monitor is not running, return 404 status.

I suggest this JSON format for monitor information:

```js
{
    "min_stop": 2,          // this is the minimum number of seconds to consider a stop
    "timeout": 10800,       // after this time the monitor will stop automatically (3 hours)
    "active_time": 13,
    "end_time": 1636058007, // epoch time, can be converted anytime
    "non_active_time": 8,
    "percentage": 61,
    "start_total_time": 1636057986,
    "stops": [
        [
            2,             // total seconds of current stop
            1636057989,    // timestamp for starting time of current stop
            1636057991     // timestamp for ending time of current stop
        ],
        [
            4,
            1636057993,
            1636057997
        ],
        [
            2,
            1636058000,
            1636058002
        ]
    ],
    "total_time": 21
}
```

**Comment by ariel434** [comment]
good job ben!
 I agree  that all the calculations need to be on the server side , i have few suggestions: 
-When we ask for server status and the monitor is off we get massage
-Maybe we want get some more info in server status perhaps
how much time the server is on  and when it starts.
-In the json the name end-time need to change to end-total-time like the start.
-We need to  allowed the user to choose how much time he want the monitor will work so we can do the api get parameter of time(1 hour ,2 hours etc.) or do some different api’s , and option that he just can start and then whenever he wants stop the monitor.
waht do you think?

**Comment by ZikriBen** [comment]
[Fixed](https://github.com/ZikriBen/timely/commit/b7233ebcf31fe10fa5dff96deb665f05725e1739) most of your suggestions.
Didn't implement more information on server status, maybe I will add later with some more logic.
